/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jospan;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Calendar;

/**
 *
 * @author admini
 */
public class InputFrame extends javax.swing.JFrame {

    /**
     * Creates new form InputFrame
     */
    public InputFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        StartButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("参加者番号を入力してください");

        NameField.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        NameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        StartButton.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        StartButton.setText("実験を始める");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NameField)
                    .addComponent(StartButton, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
        NumProcess();
    }//GEN-LAST:event_NameFieldActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        // TODO add your handling code here:
        NumProcess();
    }//GEN-LAST:event_StartButtonActionPerformed

    public void NumProcess(){
        SubNum.SubjectNumber = NameField.getText();
        try{
            File file = new File(SubNum.SubjectNumber + ".txt");
            FileWriter filewriter = new FileWriter(file, true);
            ExDate2 dow = new ExDate2();
            StringBuffer sb = new StringBuffer();
            String ls = System.getProperty("line.separator");
            sb.append(SubNum.SubjectNumber);
            sb.append(" ");
            sb.append(dow.calnow());
            sb.append(ls);
            filewriter.write(sb.toString());
            filewriter.close();
        }catch(IOException error){
            System.out.println(error);
        }
        MemOnlyIns ref = new MemOnlyIns();
        //PracticeIns ref = new PracticeIns(); //テスト用
        //TrialIns ref = new TrialIns(); //テスト用
        ref.setVisible(true);
        ref.setLocationRelativeTo(null);
        dispose();        
        
        //テスト用
        //SubNum.TimeLimit = 100;
        //SubNum.TimeLimit = 2500;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameField;
    private javax.swing.JButton StartButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}

//http://www.javaroad.jp/java_date2.htm
class ExDate2 {
  public static StringBuffer calnow() {
    Calendar cal1 = Calendar.getInstance();  //(1)オブジェクトの生成

    int year = cal1.get(Calendar.YEAR);        //(2)現在の年を取得
    int month = cal1.get(Calendar.MONTH) + 1;  //(3)現在の月を取得
    int day = cal1.get(Calendar.DATE);         //(4)現在の日を取得
    int hour = cal1.get(Calendar.HOUR_OF_DAY); //(5)現在の時を取得
    int minute = cal1.get(Calendar.MINUTE);    //(6)現在の分を取得
    int second = cal1.get(Calendar.SECOND);    //(7)現在の秒を取得

    StringBuffer sb = new StringBuffer();
    sb.append(year + "/" + month + "/" + day + " " + hour + ":" + minute + ":" + second);

    return sb;
  }
}
