/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jospan;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 *
 * @author admini
 */
public class MemTest extends javax.swing.JFrame implements ActionListener{
    javax.swing.Timer OneSecond, PresenT, AfterPresent, FeedBack;
    int MemAns = 1; //再生画面での回答番号
    int TestNum = 1; //1:記銘のみ，2:計算のみ, 3:Span2の練習，4:本番
    int BtnAns = 1; //再生画面でのボタン番号
    int MemOnlyTrial = 1; //記銘のみの試行番号
    int SpanCount = 0;//Spanのカウント，試行ごとにリセットされる
    int Score = 0;//Span得点，試行ごとにリセットされる
    List list; //ランダム用の配列。ShuffleTestで使う
    String[] CharArray = new String[12]; //記銘用の配列
    StringBuilder AnsString = new StringBuilder();
    StringBuilder ShowString = new StringBuilder();
    StringBuilder Outputs = new StringBuilder();

    /**
     * Creates new form MemTest
     */
    public MemTest() {
        initComponents();
        RecallScreen.setVisible(false);
        OneSecond = new javax.swing.Timer(1000, this);
        OneSecond.setActionCommand("OneSecond");//actionPerformed内での識別用文字列
        PresenT = new javax.swing.Timer(800, this);
        PresenT.setActionCommand("PresenT");
        AfterPresent = new javax.swing.Timer(800, this);
        AfterPresent.setActionCommand("AfterPresent");
        FeedBack = new javax.swing.Timer(2000, this);
        FeedBack.setActionCommand("FeedBack"); 
        list = ShuffleTest();
        OneSecond.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RecallScreen = new javax.swing.JPanel();
        Kyouji1 = new javax.swing.JLabel();
        Kyouji2 = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        FirstAnswer = new javax.swing.JLabel();
        SecondAnswer = new javax.swing.JLabel();
        ThirdAnswer = new javax.swing.JLabel();
        FourthAnswer = new javax.swing.JLabel();
        FifthAnswer = new javax.swing.JLabel();
        SixthAnswer = new javax.swing.JLabel();
        SeventhAnswer = new javax.swing.JLabel();
        EighthAnswer = new javax.swing.JLabel();
        Fbtn = new javax.swing.JButton();
        Hbtn = new javax.swing.JButton();
        Jbtn = new javax.swing.JButton();
        Kbtn = new javax.swing.JButton();
        Lbtn = new javax.swing.JButton();
        Nbtn = new javax.swing.JButton();
        Pbtn = new javax.swing.JButton();
        Qbtn = new javax.swing.JButton();
        Rbtn = new javax.swing.JButton();
        Sbtn = new javax.swing.JButton();
        Tbtn = new javax.swing.JButton();
        Ybtn = new javax.swing.JButton();
        Unbtn = new javax.swing.JButton();
        labelF = new javax.swing.JLabel();
        LabelK = new javax.swing.JLabel();
        LabelP = new javax.swing.JLabel();
        LabelS = new javax.swing.JLabel();
        LabelH = new javax.swing.JLabel();
        LabelL = new javax.swing.JLabel();
        LabelQ = new javax.swing.JLabel();
        LabelT = new javax.swing.JLabel();
        LAbelJ = new javax.swing.JLabel();
        LabelN = new javax.swing.JLabel();
        LabelR = new javax.swing.JLabel();
        LabelY = new javax.swing.JLabel();
        MemOnlyFeedbackPanel = new javax.swing.JPanel();
        FBText = new javax.swing.JLabel();
        CharPanel = new javax.swing.JPanel();
        SpanChar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 625));
        setMinimumSize(new java.awt.Dimension(800, 625));
        setPreferredSize(new java.awt.Dimension(800, 625));
        setResizable(false);

        RecallScreen.setMaximumSize(new java.awt.Dimension(800, 600));
        RecallScreen.setMinimumSize(new java.awt.Dimension(800, 600));
        RecallScreen.setPreferredSize(new java.awt.Dimension(800, 600));

        Kyouji1.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        Kyouji1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kyouji1.setText("提示された文字を順番に答えてください");

        Kyouji2.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        Kyouji2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kyouji2.setText("忘れたら「？」を選んでください");

        OKButton.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        OKButton.setText("OK");
        OKButton.setMaximumSize(new java.awt.Dimension(80, 50));
        OKButton.setMinimumSize(new java.awt.Dimension(80, 50));
        OKButton.setPreferredSize(new java.awt.Dimension(80, 50));
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        ResetButton.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.setMaximumSize(new java.awt.Dimension(80, 50));
        ResetButton.setMinimumSize(new java.awt.Dimension(80, 50));
        ResetButton.setPreferredSize(new java.awt.Dimension(80, 50));
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        FirstAnswer.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        FirstAnswer.setMaximumSize(new java.awt.Dimension(65, 65));
        FirstAnswer.setMinimumSize(new java.awt.Dimension(65, 65));
        FirstAnswer.setPreferredSize(new java.awt.Dimension(65, 65));

        SecondAnswer.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        SecondAnswer.setMaximumSize(new java.awt.Dimension(65, 65));
        SecondAnswer.setMinimumSize(new java.awt.Dimension(65, 65));
        SecondAnswer.setPreferredSize(new java.awt.Dimension(65, 65));

        ThirdAnswer.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        ThirdAnswer.setMaximumSize(new java.awt.Dimension(65, 65));
        ThirdAnswer.setMinimumSize(new java.awt.Dimension(65, 65));
        ThirdAnswer.setPreferredSize(new java.awt.Dimension(65, 65));

        FourthAnswer.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        FourthAnswer.setMaximumSize(new java.awt.Dimension(65, 65));
        FourthAnswer.setMinimumSize(new java.awt.Dimension(65, 65));
        FourthAnswer.setPreferredSize(new java.awt.Dimension(65, 65));

        FifthAnswer.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        FifthAnswer.setMaximumSize(new java.awt.Dimension(65, 65));
        FifthAnswer.setMinimumSize(new java.awt.Dimension(65, 65));
        FifthAnswer.setPreferredSize(new java.awt.Dimension(65, 65));

        SixthAnswer.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        SixthAnswer.setMaximumSize(new java.awt.Dimension(65, 65));
        SixthAnswer.setMinimumSize(new java.awt.Dimension(65, 65));
        SixthAnswer.setPreferredSize(new java.awt.Dimension(65, 65));

        SeventhAnswer.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        SeventhAnswer.setMaximumSize(new java.awt.Dimension(65, 65));
        SeventhAnswer.setMinimumSize(new java.awt.Dimension(65, 65));
        SeventhAnswer.setPreferredSize(new java.awt.Dimension(65, 65));

        EighthAnswer.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        EighthAnswer.setMaximumSize(new java.awt.Dimension(65, 65));
        EighthAnswer.setMinimumSize(new java.awt.Dimension(65, 65));
        EighthAnswer.setPreferredSize(new java.awt.Dimension(65, 65));

        Fbtn.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        Fbtn.setMaximumSize(new java.awt.Dimension(75, 50));
        Fbtn.setMinimumSize(new java.awt.Dimension(75, 50));
        Fbtn.setPreferredSize(new java.awt.Dimension(75, 50));
        Fbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FbtnActionPerformed(evt);
            }
        });

        Hbtn.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        Hbtn.setMaximumSize(new java.awt.Dimension(75, 50));
        Hbtn.setMinimumSize(new java.awt.Dimension(75, 50));
        Hbtn.setPreferredSize(new java.awt.Dimension(75, 50));
        Hbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HbtnActionPerformed(evt);
            }
        });

        Jbtn.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        Jbtn.setMaximumSize(new java.awt.Dimension(75, 50));
        Jbtn.setMinimumSize(new java.awt.Dimension(75, 50));
        Jbtn.setPreferredSize(new java.awt.Dimension(75, 50));
        Jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnActionPerformed(evt);
            }
        });

        Kbtn.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        Kbtn.setMaximumSize(new java.awt.Dimension(75, 50));
        Kbtn.setMinimumSize(new java.awt.Dimension(75, 50));
        Kbtn.setPreferredSize(new java.awt.Dimension(75, 50));
        Kbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KbtnActionPerformed(evt);
            }
        });

        Lbtn.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        Lbtn.setMaximumSize(new java.awt.Dimension(75, 50));
        Lbtn.setMinimumSize(new java.awt.Dimension(75, 50));
        Lbtn.setPreferredSize(new java.awt.Dimension(75, 50));
        Lbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LbtnActionPerformed(evt);
            }
        });

        Nbtn.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        Nbtn.setMaximumSize(new java.awt.Dimension(75, 50));
        Nbtn.setMinimumSize(new java.awt.Dimension(75, 50));
        Nbtn.setPreferredSize(new java.awt.Dimension(75, 50));
        Nbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NbtnActionPerformed(evt);
            }
        });

        Pbtn.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        Pbtn.setMaximumSize(new java.awt.Dimension(75, 50));
        Pbtn.setMinimumSize(new java.awt.Dimension(75, 50));
        Pbtn.setPreferredSize(new java.awt.Dimension(75, 50));
        Pbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PbtnActionPerformed(evt);
            }
        });

        Qbtn.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        Qbtn.setMaximumSize(new java.awt.Dimension(75, 50));
        Qbtn.setMinimumSize(new java.awt.Dimension(75, 50));
        Qbtn.setPreferredSize(new java.awt.Dimension(75, 50));
        Qbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QbtnActionPerformed(evt);
            }
        });

        Rbtn.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        Rbtn.setMaximumSize(new java.awt.Dimension(75, 50));
        Rbtn.setMinimumSize(new java.awt.Dimension(75, 50));
        Rbtn.setPreferredSize(new java.awt.Dimension(75, 50));
        Rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnActionPerformed(evt);
            }
        });

        Sbtn.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        Sbtn.setMaximumSize(new java.awt.Dimension(75, 50));
        Sbtn.setMinimumSize(new java.awt.Dimension(75, 50));
        Sbtn.setPreferredSize(new java.awt.Dimension(75, 50));
        Sbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnActionPerformed(evt);
            }
        });

        Tbtn.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        Tbtn.setMaximumSize(new java.awt.Dimension(75, 50));
        Tbtn.setMinimumSize(new java.awt.Dimension(75, 50));
        Tbtn.setPreferredSize(new java.awt.Dimension(75, 50));
        Tbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbtnActionPerformed(evt);
            }
        });

        Ybtn.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        Ybtn.setMaximumSize(new java.awt.Dimension(75, 50));
        Ybtn.setMinimumSize(new java.awt.Dimension(75, 50));
        Ybtn.setPreferredSize(new java.awt.Dimension(75, 50));
        Ybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YbtnActionPerformed(evt);
            }
        });

        Unbtn.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        Unbtn.setText("?");
        Unbtn.setMaximumSize(new java.awt.Dimension(75, 50));
        Unbtn.setMinimumSize(new java.awt.Dimension(75, 50));
        Unbtn.setPreferredSize(new java.awt.Dimension(75, 50));
        Unbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnbtnActionPerformed(evt);
            }
        });

        labelF.setFont(new java.awt.Font("メイリオ", 0, 36)); // NOI18N
        labelF.setText("F");

        LabelK.setFont(new java.awt.Font("メイリオ", 0, 36)); // NOI18N
        LabelK.setText("K");

        LabelP.setFont(new java.awt.Font("メイリオ", 0, 36)); // NOI18N
        LabelP.setText("P");

        LabelS.setFont(new java.awt.Font("メイリオ", 0, 36)); // NOI18N
        LabelS.setText("S");

        LabelH.setFont(new java.awt.Font("メイリオ", 0, 36)); // NOI18N
        LabelH.setText("H");

        LabelL.setFont(new java.awt.Font("メイリオ", 0, 36)); // NOI18N
        LabelL.setText("L");

        LabelQ.setFont(new java.awt.Font("メイリオ", 0, 36)); // NOI18N
        LabelQ.setText("Q");

        LabelT.setFont(new java.awt.Font("メイリオ", 0, 36)); // NOI18N
        LabelT.setText("T");

        LAbelJ.setFont(new java.awt.Font("メイリオ", 0, 36)); // NOI18N
        LAbelJ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LAbelJ.setText("J");

        LabelN.setFont(new java.awt.Font("メイリオ", 0, 36)); // NOI18N
        LabelN.setText("N");

        LabelR.setFont(new java.awt.Font("メイリオ", 0, 36)); // NOI18N
        LabelR.setText("R");

        LabelY.setFont(new java.awt.Font("メイリオ", 0, 36)); // NOI18N
        LabelY.setText("Y");

        javax.swing.GroupLayout RecallScreenLayout = new javax.swing.GroupLayout(RecallScreen);
        RecallScreen.setLayout(RecallScreenLayout);
        RecallScreenLayout.setHorizontalGroup(
            RecallScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Kyouji1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Kyouji2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(RecallScreenLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(Fbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(labelF)
                .addGap(79, 79, 79)
                .addComponent(Hbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(LabelH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Jbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LAbelJ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RecallScreenLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(Kbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(LabelK)
                .addGap(76, 76, 76)
                .addComponent(Lbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(LabelL)
                .addGap(57, 57, 57)
                .addComponent(Nbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(LabelN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RecallScreenLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(Pbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(LabelP)
                .addGap(79, 79, 79)
                .addComponent(Qbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(LabelQ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Rbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(LabelR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RecallScreenLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(Sbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(LabelS)
                .addGap(77, 77, 77)
                .addComponent(Tbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(LabelT)
                .addGap(54, 54, 54)
                .addComponent(Ybtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(LabelY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RecallScreenLayout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(Unbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RecallScreenLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(FirstAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(SecondAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(ThirdAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(FourthAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(FifthAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(SixthAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(SeventhAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(EighthAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RecallScreenLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        RecallScreenLayout.setVerticalGroup(
            RecallScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RecallScreenLayout.createSequentialGroup()
                .addComponent(Kyouji1)
                .addGap(6, 6, 6)
                .addComponent(Kyouji2)
                .addGap(20, 20, 20)
                .addGroup(RecallScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelF)
                    .addComponent(Hbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelH)
                    .addComponent(LAbelJ)
                    .addComponent(Jbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(RecallScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Kbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelK)
                    .addComponent(Lbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelL)
                    .addComponent(Nbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelN))
                .addGap(20, 20, 20)
                .addGroup(RecallScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RecallScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Pbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelP)
                        .addComponent(Rbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(RecallScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LabelQ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Qbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(RecallScreenLayout.createSequentialGroup()
                        .addComponent(LabelR)
                        .addGap(2, 2, 2)))
                .addGap(20, 20, 20)
                .addGroup(RecallScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelS)
                    .addComponent(LabelT)
                    .addComponent(Tbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ybtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelY))
                .addGap(20, 20, 20)
                .addComponent(Unbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(RecallScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecondAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThirdAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FourthAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FifthAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SixthAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeventhAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EighthAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(RecallScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        MemOnlyFeedbackPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        MemOnlyFeedbackPanel.setMinimumSize(new java.awt.Dimension(800, 600));

        FBText.setFont(new java.awt.Font("メイリオ", 0, 24)); // NOI18N
        FBText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout MemOnlyFeedbackPanelLayout = new javax.swing.GroupLayout(MemOnlyFeedbackPanel);
        MemOnlyFeedbackPanel.setLayout(MemOnlyFeedbackPanelLayout);
        MemOnlyFeedbackPanelLayout.setHorizontalGroup(
            MemOnlyFeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FBText, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        MemOnlyFeedbackPanelLayout.setVerticalGroup(
            MemOnlyFeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FBText, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        CharPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        CharPanel.setMinimumSize(new java.awt.Dimension(800, 600));

        SpanChar.setFont(new java.awt.Font("メイリオ", 0, 48)); // NOI18N
        SpanChar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout CharPanelLayout = new javax.swing.GroupLayout(CharPanel);
        CharPanel.setLayout(CharPanelLayout);
        CharPanelLayout.setHorizontalGroup(
            CharPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SpanChar, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        CharPanelLayout.setVerticalGroup(
            CharPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SpanChar, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RecallScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(MemOnlyFeedbackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(CharPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RecallScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(MemOnlyFeedbackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(CharPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnbtnActionPerformed
        ShowAns(MemAns, "?"); //?はボタン内の文字を変更しない
    }//GEN-LAST:event_UnbtnActionPerformed

    private void YbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YbtnActionPerformed
        Ybtn.setText(Integer.toString(BtnAns));
        ShowAns(MemAns, "Y");
    }//GEN-LAST:event_YbtnActionPerformed

    private void TbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbtnActionPerformed
        Tbtn.setText(Integer.toString(BtnAns));
        ShowAns(MemAns, "T");
    }//GEN-LAST:event_TbtnActionPerformed

    private void SbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnActionPerformed
        Sbtn.setText(Integer.toString(BtnAns));
        ShowAns(MemAns, "S");
    }//GEN-LAST:event_SbtnActionPerformed

    private void RbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnActionPerformed
        Rbtn.setText(Integer.toString(BtnAns));
        ShowAns(MemAns, "R");
    }//GEN-LAST:event_RbtnActionPerformed

    private void QbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QbtnActionPerformed
        Qbtn.setText(Integer.toString(BtnAns));
        ShowAns(MemAns, "Q");
    }//GEN-LAST:event_QbtnActionPerformed

    private void PbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PbtnActionPerformed
        Pbtn.setText(Integer.toString(BtnAns));
        ShowAns(MemAns, "P");
    }//GEN-LAST:event_PbtnActionPerformed

    private void NbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NbtnActionPerformed
        Nbtn.setText(Integer.toString(BtnAns));
        ShowAns(MemAns, "N");
    }//GEN-LAST:event_NbtnActionPerformed

    private void LbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LbtnActionPerformed
        Lbtn.setText(Integer.toString(BtnAns));
        ShowAns(MemAns,"L");
    }//GEN-LAST:event_LbtnActionPerformed

    private void KbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KbtnActionPerformed
        Kbtn.setText(Integer.toString(BtnAns));
        ShowAns(MemAns, "K");
    }//GEN-LAST:event_KbtnActionPerformed

    private void JbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnActionPerformed
        Jbtn.setText(Integer.toString(BtnAns));
        ShowAns(MemAns, "J");
    }//GEN-LAST:event_JbtnActionPerformed

    private void HbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HbtnActionPerformed
        Hbtn.setText(Integer.toString(BtnAns));
        ShowAns(MemAns, "H");
    }//GEN-LAST:event_HbtnActionPerformed

    private void FbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FbtnActionPerformed
        Fbtn.setText(Integer.toString(BtnAns)); //SetTextしてからMemAns+1をしないと数字がずれる
        ShowAns(MemAns, "F");
    }//GEN-LAST:event_FbtnActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        ResetAnswer();
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        //System.out.println(Integer.toString(MemAns));
        //System.out.println(ShowString);
        //System.out.println(AnsString);
        //System.out.println(ShowString.length());
        RecallScreen.setVisible(false);
        MemOnlyFeedbackPanel.setVisible(true);
        CharCalc();
        //System.out.println(Score);
        FBText.setText("あなたは" + SpanCount + "文字中" + Score + "文字思い出しました");
        ResetAnswer();
        ResetValue();
        BtnAns = 1;
        FeedBack.start();
    }//GEN-LAST:event_OKButtonActionPerformed

    public void ShowAns(int Ans, String Character){
        if (Ans == 1 && MemAns <= 8){
            FirstAnswer.setText(Character);
            MemAns = MemAns + 1;
            BtnAns = MemAns;
        }
        if (Ans == 2 && MemAns <= 8){
            SecondAnswer.setText(Character);
            MemAns = MemAns + 1;
            BtnAns = MemAns;
        }
        if (Ans == 3 && MemAns <= 8){
            ThirdAnswer.setText(Character);
            MemAns = MemAns + 1;
            BtnAns = MemAns;
        }
        if (Ans == 4 && MemAns <= 8){
            FourthAnswer.setText(Character);
            MemAns = MemAns + 1;
            BtnAns = MemAns;
        }
        if (Ans == 5 && MemAns <= 8){
            FifthAnswer.setText(Character);
            MemAns = MemAns + 1;
            BtnAns = MemAns;
        }
        if (Ans == 6 && MemAns <= 8){
            SixthAnswer.setText(Character);
            MemAns = MemAns + 1;
            BtnAns = MemAns;
        }
        if (Ans == 7 && MemAns <= 8){
            SeventhAnswer.setText(Character);
            MemAns = MemAns + 1;
            BtnAns = MemAns;
        }
        if (Ans == 8){
            EighthAnswer.setText(Character);
            MemAns = MemAns + 1;
        }
        if (MemAns <= 9){ //CharCalc用にMemAnsを8から9に変更した
            if (AnsString.length() <= 8){
            AnsString.append(String.format("%s", Character));
            System.out.println(AnsString);
            }
        }
    }
    
    public void ResetAnswer() {
        FirstAnswer.setText("");
        SecondAnswer.setText("");
        ThirdAnswer.setText("");
        FourthAnswer.setText("");
        FifthAnswer.setText("");
        SixthAnswer.setText("");
        SeventhAnswer.setText("");
        EighthAnswer.setText("");
        Fbtn.setText("");
        Hbtn.setText("");
        Jbtn.setText("");
        Kbtn.setText("");
        Lbtn.setText("");
        Nbtn.setText("");
        Pbtn.setText("");
        Qbtn.setText("");
        Rbtn.setText("");
        Sbtn.setText("");
        Tbtn.setText("");
        Ybtn.setText("");
        MemAns = 1;
        BtnAns = 1;
        AnsString.setLength(0);
    }
    
    public void CharCalc(){
        if (AnsString.length() <= ShowString.length()){
            AnsSmaller();
        }else
        {
            ShowSmaller();
        }
        String ls = System.getProperty("line.separator");
        Outputs.append(ShowString);
        Outputs.append(" ");
        Outputs.append(AnsString);
        Outputs.append(" ");
        Outputs.append(Score);
        Outputs.append(ls);
        //System.out.println(Score);
    }

    public void AnsSmaller(){
        for(int i = 0; i < AnsString.length(); i++){
            if (AnsString.length() == 0){
                Score = 0;
            }else if (AnsString.charAt(i) == ShowString.charAt(i)){
                Score = Score + 1;
            }
        }
        System.out.println("AnsBigger");
    }

    public void ShowSmaller(){
        for(int i = 0; i < ShowString.length(); i++){
            if (AnsString.length() == 0){
                Score = 0;
            }else if (ShowString.charAt(i) == AnsString.charAt(i)){
                Score = Score + 1;
            }
        }
        System.out.println("ShowBigger");
    }    
    
    public void ResetValue(){
        ShowString.setLength(0);
        AnsString.setLength(0);
        SpanCount = 0;
        Score = 0;
    }

    private static List ShuffleTest(){
        ArrayList<Integer> list = new ArrayList<Integer>();
        for (int i = 0; i <= 11; i++){
            list.add(i);
        }
        //System.out.println(list);
        Collections.shuffle(list);
        //System.out.println(list);
        return list;
    }
    
    public void PrintChar(int i){
        CharArray[0] = "F";
        CharArray[1] = "H";
        CharArray[2] = "J";
        CharArray[3] = "K";
        CharArray[4] = "L";
        CharArray[5] = "N";
        CharArray[6] = "P";
        CharArray[7] = "Q";
        CharArray[8] = "R";
        CharArray[9] = "S";
        CharArray[10] = "T";
        CharArray[11] = "Y";
        
        SpanChar.setText(CharArray[i]);
        ShowString.append(String.format("%s", CharArray[i]));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CharPanel;
    private javax.swing.JLabel EighthAnswer;
    private javax.swing.JLabel FBText;
    private javax.swing.JButton Fbtn;
    private javax.swing.JLabel FifthAnswer;
    private javax.swing.JLabel FirstAnswer;
    private javax.swing.JLabel FourthAnswer;
    private javax.swing.JButton Hbtn;
    private javax.swing.JButton Jbtn;
    private javax.swing.JButton Kbtn;
    private javax.swing.JLabel Kyouji1;
    private javax.swing.JLabel Kyouji2;
    private javax.swing.JLabel LAbelJ;
    private javax.swing.JLabel LabelH;
    private javax.swing.JLabel LabelK;
    private javax.swing.JLabel LabelL;
    private javax.swing.JLabel LabelN;
    private javax.swing.JLabel LabelP;
    private javax.swing.JLabel LabelQ;
    private javax.swing.JLabel LabelR;
    private javax.swing.JLabel LabelS;
    private javax.swing.JLabel LabelT;
    private javax.swing.JLabel LabelY;
    private javax.swing.JButton Lbtn;
    private javax.swing.JPanel MemOnlyFeedbackPanel;
    private javax.swing.JButton Nbtn;
    private javax.swing.JButton OKButton;
    private javax.swing.JButton Pbtn;
    private javax.swing.JButton Qbtn;
    private javax.swing.JButton Rbtn;
    private javax.swing.JPanel RecallScreen;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton Sbtn;
    private javax.swing.JLabel SecondAnswer;
    private javax.swing.JLabel SeventhAnswer;
    private javax.swing.JLabel SixthAnswer;
    private javax.swing.JLabel SpanChar;
    private javax.swing.JButton Tbtn;
    private javax.swing.JLabel ThirdAnswer;
    private javax.swing.JButton Unbtn;
    private javax.swing.JButton Ybtn;
    private javax.swing.JLabel labelF;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        String cmd = e.getActionCommand();
        if(cmd.equals("OneSecond")){
            //System.out.println("O");
            OneSecond.stop();
            if (TestNum == 1){
                CharPanel.setVisible(true);
                PresenT.start();
            }
        }
        if(cmd.equals("PresenT")){
            if (TestNum == 1){
                int PrintCount = (int) list.get(SpanCount);
                //System.out.println(SpanCount);
                PrintChar(PrintCount);
                SpanCount = SpanCount + 1;
            }
            if (TestNum == 1 && SpanCount == 2){
                PresenT.stop();
                AfterPresent.start();
            }
        }
        if(cmd.equals("AfterPresent")){
            AfterPresent.stop();
            CharPanel.setVisible(false);
            RecallScreen.setVisible(true);
            SpanChar.setText(""); //消しておかないと次の試行に残る
        }
        if(cmd.equals("FeedBack")){
            //System.out.println("F");
            if (TestNum == 1){
                FeedBack.stop();
                MemOnlyFeedbackPanel.setVisible(false);
                list = ShuffleTest();
                MemOnlyTrial = MemOnlyTrial + 1;
                OneSecond.start();
            }
            if (TestNum == 1 && MemOnlyTrial > 3){
                OneSecond.stop();
                FeedBack.stop();
                TestNum = TestNum + 1; //練習試行は3回で終わり
                try{
                    File file = new File(SubNum.SubjectNumber + ".txt");
                    FileWriter filewriter = new FileWriter(file, true);
                    filewriter.write(Outputs.toString());
                    filewriter.close();
                }catch(IOException error){
                    System.out.println(error);
                }
                MathIns ref = new MathIns();//計算練習にうつる
                ref.setVisible(true);
                ref.setLocationRelativeTo(null);
                dispose();
            }
        }
    }
}
